import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useAccount } from 'wagmi'
import { useDynamicContext } from '@dynamic-labs/sdk-react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const account = useAccount()
  const { user , primaryWallet, setShowAuthFlow } = useDynamicContext()
  console.log("Home: account is %o, user is %o, primaryWallet is %o", account, user, primaryWallet)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div key='1'>Wagmi Account: {account.address ? `Connected to ${account.address}` : `Not connected`}</div>
        <div key='2'>Dynamic user: {user ? JSON.stringify(user, null, 2) : 'Undefined'}</div>
        <div key='3'>Dynamic primaryWallet: {primaryWallet ? JSON.stringify(primaryWallet, null, 2) : 'Undefined'}</div>
        <button onClick={() => setShowAuthFlow(true)}>Connect</button>
      </main>
    </>
  )
}
